version: '3.8'

services:
  investment-ui:
    container_name: am_investment_ui
    build:
      context: ../
      dockerfile: am-investment-ui/Dockerfile
    ports:
      - "9000:80"
    labels:
      - "traefik.enable=true"
      # This is the main landing page, so we use PathPrefix(`/`) with a lower priority
      - "traefik.http.routers.investment-ui.rule=Host(`am.munish.org`) && PathPrefix(`/`)"
      - "traefik.http.routers.investment-ui.entrypoints=web"
      - "traefik.http.services.investment-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.investment-ui.priority=1"
    networks:
      - am-infra_am-net
    restart: unless-stopped

networks:
  am-infra_am-net:
    external: true
